### ISSUE TITLE
Upgrade Phoenix to 1.5

### ISSUE THREAD

**Issue by diegoliberman** [instedd/ask#1963]
**Todo:**

- [x] Upgrade Coherence (two choices):
  - ~~continue to upgrade [our fork](https://github.com/smpallen99/coherence/branches/v0.3)~~
  - upgrade to [latest master](https://github.com/smpallen99/coherence) -> see #2036
- [ ] Follow the [upgrade guide](https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f)
  - [ ] upgrade dependencies
  - [ ] PubSub 2.0 changes
  - [ ] update layouts
  - [ ] update tests
- [ ] ...

**Consider:**

- [ ] Upgrade Elixir to 1.10+
